global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'nvidia'
    scrape_interval: 5s
    static_configs:
      - targets: ['nvidia-gpu-exporter:9835']